### ISSUE TITLE
AttributeError: module 'onnx' has no attribute 'load_from_string'

### ISSUE THREAD

**Issue by jyashi** [harishanand95/diffusers#15]
### Describe the bug

On running `python ./save_onnx.py` I get 👇 

`Traceback (most recent call last):
  File "C:\Users\Nav\Documents\stableDiffusion\diffusers\examples\inference\save_onnx.py", line 66, in <module>
    convert_to_onnx(pipe.unet, pipe.vae.post_quant_conv, pipe.vae.decoder, text_encoder, height=512, width=512)
  File "C:\Users\Nav\Documents\stableDiffusion\diffusers\examples\inference\save_onnx.py", line 42, in convert_to_onnx
    torch.onnx.export(traced_model, check_inputs[0], "onnx/unet.onnx",
  File "C:\Python310\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Python310\lib\site-packages\torch\onnx\utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "C:\Python310\lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 228, in _add_onnxscript_fn
    model_proto = onnx.load_from_string(model_bytes)
AttributeError: module 'onnx' has no attribute 'load_from_string'`

### System Info

```shell

Windows 10
AMD Graphics card
Ryzen CPU
Python 3.10.5
Diffusers 4.24.0
```

**Comment by jyashi** [comment]
Got it running by `pip install --upgrade onnx`
