### ISSUE TITLE
RuntimeError in save_onnx.py

### ISSUE THREAD

**Issue by kg333** [harishanand95/diffusers#5]
### Describe the bug

I'm attempting to follow the instructions [here](https://github.com/harishanand95/diffusers/blob/dml/examples/inference/readme.md#instructions-for-onnx-dml-execution-on-windows) for using Stable Diffusion on AMD under WIndows, and getting the following traceback at the "Create ONNX files" step:

```
C:\ProgramData\Miniconda3\lib\site-packages\diffusers\models\resnet.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
Traceback (most recent call last):
  File "c:\working\diffusers\examples\inference\save_onnx.py", line 66, in <module>
    convert_to_onnx(pipe.unet, pipe.vae.post_quant_conv, pipe.vae.decoder, text_encoder, height=512, width=512)
  File "c:\working\diffusers\examples\inference\save_onnx.py", line 41, in convert_to_onnx
    traced_model = torch.jit.trace(unet, check_inputs[0], check_inputs=[check_inputs[1]], strict=True)
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\jit\_trace.py", line 750, in trace
    return trace_module(
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\jit\_trace.py", line 967, in trace_module
    module._c._create_method_from_trace(
RuntimeError: Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
```

Following the suggestion and changing save_onnx.py:41 to:
``` traced_model = torch.jit.trace(unet, check_inputs[0], check_inputs=[check_inputs[1]], strict=False)```

results in:
```
WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
Traceback (most recent call last):
  File "c:\working\diffusers\examples\inference\save_onnx.py", line 66, in <module>
    convert_to_onnx(pipe.unet, pipe.vae.post_quant_conv, pipe.vae.decoder, text_encoder, height=512, width=512)
  File "c:\working\diffusers\examples\inference\save_onnx.py", line 42, in convert_to_onnx
    torch.onnx.export(traced_model, check_inputs[0], "onnx/unet.onnx",
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\onnx\__init__.py", line 350, in export
    return utils.export(
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\onnx\utils.py", line 163, in export
    _export(
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\onnx\utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\onnx\utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\onnx\utils.py", line 308, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\onnx\__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Users\[user]\AppData\Roaming\Python\Python39\site-packages\torch\onnx\utils.py", line 1421, in _run_symbolic_function
    raise symbolic_registry.UnsupportedOperatorError(
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator prim::DictConstruct to ONNX opset version 16 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

### System Info

```shell
AMD 5700XT using Python 3.9.12, ort_nightly_directml-1.13.0.dev20220908001-cp39-cp39-win_amd64.whl.
transformers 4.21.3
ftfy 6.1.1
scipy 1.9.0
```

**Comment by kg333** [comment]
Your more recent walkthrough works for me:
https://gist.github.com/harishanand95/75f4515e6187a6aa3261af6ac6f61269

pip reports the same versions for transformers, ftfy, and scipy.

I'm new to the whole ML thing: is there a way to do img2img.py using that method?

**Comment by kg333** [comment]
Apologies, I just need to RTFM.  How to use image to image is described here:
https://pypi.org/project/diffusers/

Thanks for putting these walkthroughs together!  To my knowledge, this is the only working method for an AMD 5700XT under Windows right now.
